
CREATE TABLE `fp_capital_pool_car_rel` (
  `cpc_rel_id` bigint(19) NOT NULL AUTO_INCREMENT COMMENT '主键Id',
  `capital_pool_id` varchar(32) NOT NULL COMMENT '资金池Id',
  `debt_id` varchar(32) NOT NULL COMMENT '借据Id',
  `car_id` bigint(19) NOT NULL COMMENT '车辆Id',
  `amount` bigint(19) NOT NULL COMMENT '金额',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `status` int(4) NOT NULL COMMENT '状态',
  PRIMARY KEY (`cpc_rel_id`),
  UNIQUE KEY `cpc_rel_id_UNIQUE` (`cpc_rel_id`)
) ENGINE=InnoDB AUTO_INCREMENT=168 DEFAULT CHARSET=utf8;

CREATE TABLE `fp_capital_pool_debt_rel` (
  `cpd_rel_id` bigint(19) NOT NULL AUTO_INCREMENT,
  `capital_pool_id` varchar(32) NOT NULL,
  `debt_id` varchar(32) NOT NULL COMMENT '目标金额',
  `amount` bigint(19) NOT NULL DEFAULT '0' COMMENT '当前资金金额(分)',
  `car_num` int(10) NOT NULL,
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` int(4) NOT NULL COMMENT '0  - 初始化\n10 -  通过\n99 -  拒绝\n100- 已完成\n-1 - 删除',
  `debt_amount` bigint(19) NOT NULL DEFAULT '0',
  PRIMARY KEY (`cpd_rel_id`)
) ENGINE=InnoDB AUTO_INCREMENT=67 DEFAULT CHARSET=utf8 COMMENT='资金池';

CREATE TABLE `fp_capital_pool` (
  `capital_pool_id` varchar(32) NOT NULL,
  `amount` bigint(19) NOT NULL DEFAULT '0' COMMENT '当前资金金额(分)',
  `target_amount` bigint(19) NOT NULL COMMENT '目标资金',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `status` int(4) NOT NULL COMMENT '0 - 初始化\n10 - 待补充资金\n20 - 资金池已满\n30 - 锁定\n100 - 完成\n-1 - 已删除',
  PRIMARY KEY (`capital_pool_id`),
  UNIQUE KEY `capital_pool_id_UNIQUE` (`capital_pool_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='资金池';

CREATE TABLE `fp_cession_proceeds` (
  `proceed_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键Id',
  `proceed_no` varchar(45) DEFAULT NULL COMMENT '结算单号',
  `proceed_type` tinyint(4) DEFAULT '0' COMMENT '结算类型',
  `start_time` datetime DEFAULT NULL COMMENT '计息开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '计息结束时间',
  `interest` decimal(20,6) DEFAULT '0.000000' COMMENT '利息',
  `interest_amount` decimal(25,6) DEFAULT '0.000000' COMMENT '计息金额',
  `proceed_amount` decimal(25,6) DEFAULT '0.000000' COMMENT '结算金额',
  `proceed_time` datetime DEFAULT NULL COMMENT '结算时间',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `cession_id` varchar(45) DEFAULT NULL COMMENT '债转项目ID',
  PRIMARY KEY (`proceed_id`),
  UNIQUE KEY `proceed_id_UNIQUE` (`proceed_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `fp_collection` (
  `collection_no` varchar(31) NOT NULL COMMENT '催收编号',
  `debt_id` varchar(31) NOT NULL COMMENT '借据id',
  `debt_balance_principal` decimal(24,2) DEFAULT '0.00' COMMENT '借据余额本金',
  `debt_balance_interest` decimal(24,2) DEFAULT '0.00' COMMENT '借据余额利息',
  `debt_balance_interest_and_principal` decimal(24,2) DEFAULT '0.00' COMMENT '借据余额本息和',
  `collection_cost` decimal(24,2) DEFAULT '0.00' COMMENT '催收成本',
  `collection_type` int(11) DEFAULT '0' COMMENT '催收方式 0未知 1 催收函 2 电话崔收 3 短信/微信催收 4 上门催收',
  `executor_id` varchar(31) DEFAULT NULL COMMENT '对应db_auth库中的auth_staff表中的staffId',
  `executor` varchar(31) DEFAULT '' COMMENT '实施人',
  `execute_date` timestamp NULL DEFAULT NULL COMMENT '实施日期',
  `procedure_location` int(11) DEFAULT NULL COMMENT '手续位置 0未知 1未邮寄 2大区办公室 3杭州公司 4资方 5三方监管',
  `car_location` int(11) DEFAULT NULL COMMENT '车辆位置 0 未知 1厂家未发车 2物流中 3已入库',
  `status` int(11) DEFAULT '0' COMMENT '状态 -1 已删除 0 未开始 1 进行中 2 已完成',
  `memo` varchar(255) DEFAULT '' COMMENT '备注',
  `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP,
  `create_source` int(11) DEFAULT '0' COMMENT '创建来源 0H5 1后台',
  `collection_certificate_list` varchar(1024) DEFAULT NULL COMMENT '催收凭证url和文件名集合',
  `other_file_list` varchar(1024) DEFAULT NULL COMMENT '其他文件集合',
  PRIMARY KEY (`collection_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='催收记录表';

CREATE TABLE `fp_car_debt_record` (
  `car_debt_record_no` varchar(40) NOT NULL COMMENT '计息记录遍号',
  `debt_id` varchar(40) DEFAULT NULL COMMENT '借据号',
  `order_no` varchar(40) NOT NULL COMMENT '订单编号',
  `car_id` bigint(20) DEFAULT NULL COMMENT '车辆id',
  `car_unique` varchar(40) DEFAULT NULL COMMENT '车架号',
  `principal` decimal(24,2) DEFAULT '0.00' COMMENT '本金(借款人)',
  `capital_principal` decimal(24,2) DEFAULT '0.00' COMMENT '资方本金',
  `core_price` decimal(24,2) DEFAULT '0.00' COMMENT '核价',
  `rate` decimal(10,6) DEFAULT '0.000000' COMMENT '利率',
  `start_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
  `borrower_end_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '结束日期（借款人）',
  `capital_rate` decimal(10,6) DEFAULT '0.000000' COMMENT '资方利率',
  `capital_end_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '结束日期（资方）',
  `duration_borrower` int(11) DEFAULT '0' COMMENT '期限（借款人）',
  `duration_capital` int(11) DEFAULT '0' COMMENT '期限（资方）',
  `borrower_accrual` decimal(24,2) DEFAULT '0.00' COMMENT '借款人利息',
  `capital_accrual` decimal(24,2) DEFAULT '0.00' COMMENT '资方利息',
  `net_accrual` decimal(24,2) DEFAULT '0.00' COMMENT '净利息',
  `favorable_amount` decimal(24,2) DEFAULT '0.00' COMMENT '优惠金额',
  `sub_accrual` decimal(24,2) DEFAULT '0.00' COMMENT '利息差',
  `dept_status` int(11) DEFAULT NULL COMMENT '借据状态 0带出账 1 已出账 2预期 3保全中 4结清',
  `repayment_no` varchar(40) DEFAULT NULL COMMENT '还款结算单号',
  `repayment_status` int(11) DEFAULT '0' COMMENT '还款状态 0 待还款 1 已还款',
  `gtm_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gtm_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `memo` varchar(64) DEFAULT NULL COMMENT '备注',
  `repayment_date` datetime DEFAULT NULL COMMENT '还款时间',
  `cal_status` int(11) DEFAULT '0' COMMENT '是否计算成功 1 成功 0 不成功',
  `today_borrower_accrual` decimal(24,2) DEFAULT NULL COMMENT '当天借款人利息',
  `today_capital_accrual` decimal(24,2) DEFAULT '0.00' COMMENT '当天资方利息',
  PRIMARY KEY (`car_debt_record_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='车辆每日计息记录';

CREATE TABLE `fp_debt_cession` (
  `debt_cession_id` varchar(32) NOT NULL COMMENT '主键Id',
  `cession_name` varchar(255) NOT NULL COMMENT '项目名称',
  `cession_amount` bigint(19) NOT NULL COMMENT '债转金额(分)',
  `cession_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '1-兜底\n2-不兜底',
  `capital_id` bigint(19) DEFAULT NULL COMMENT '受让人(资方id)',
  `capital_name` varchar(45) DEFAULT NULL COMMENT '资方名称',
  `capital_pool_id` varchar(32) NOT NULL COMMENT '资金池',
  `contract_id` bigint(19) DEFAULT NULL COMMENT '合同id',
  `cession_start_time` bigint(19) NOT NULL COMMENT '债转开始时间',
  `cession_end_time` bigint(19) NOT NULL COMMENT '债转结束时间',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `status` int(4) NOT NULL DEFAULT '0' COMMENT '0-初始化\n10-资产已打包\n20 资方已确认,待打款\n30 债权转移已生效\n100 完成\n\n-1 关闭',
  `user_id` varchar(32) DEFAULT NULL COMMENT '责任人',
  `user_name` varchar(45) DEFAULT NULL COMMENT '备注',
  `rate` decimal(10,6) DEFAULT '0.000000' COMMENT '利率',
  `asset_approve_type` tinyint(4) DEFAULT NULL COMMENT '资产审批类型\n0:不审批 \n1:需审批\n2:不生成审批，推送审批\n3:生成审批，推送不审批',
  `project_approve_type` tinyint(4) DEFAULT NULL COMMENT '资产审批类型\n0:不审批\n1:需审批',
  `memo` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`debt_cession_id`),
  UNIQUE KEY `debt_cession_id_UNIQUE` (`debt_cession_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='债转项目';

CREATE TABLE `fp_debt_collection_log` (
  `todo_id` varchar(31) NOT NULL COMMENT '催收流水号',
  `debt_id` varchar(31) NOT NULL COMMENT '借据流水号',
  `collection_id` varchar(31) DEFAULT NULL COMMENT '催收id',
  `solve_id` varchar(31) DEFAULT NULL COMMENT '化解id',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '催收记录状态：1已处理 未处理0  无效-1',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `instance_id` varchar(45) DEFAULT NULL COMMENT '流程Id',
  `overdue_principal` decimal(24,6) DEFAULT '0.000000' COMMENT '逾期本金',
  `overdue_interest` decimal(24,6) DEFAULT '0.000000' COMMENT '逾期利息',
  `overdue_principal_and_interest` decimal(24,6) DEFAULT '0.000000' COMMENT '逾期本息和',
  `overdue_time` datetime COMMENT '逾期日期',
  `overdue_daytime` bigint(20) DEFAULT NULL COMMENT '逾期天数',
  `manager_id` bigint(20) DEFAULT NULL COMMENT '逾期天数',
  PRIMARY KEY (`todo_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='超期代办';

CREATE TABLE `fp_car_debt` (
  `car_debt_flow_no` varchar(40) NOT NULL COMMENT '计息流水号',
  `debt_id` varchar(40) DEFAULT NULL COMMENT '借据号',
  `order_no` varchar(40) NOT NULL COMMENT '订单编号',
  `car_id` bigint(20) DEFAULT NULL COMMENT '车辆id',
  `car_unique` varchar(40) DEFAULT NULL COMMENT '车架号',
  `principal` decimal(24,2) DEFAULT '0.00' COMMENT '本金(借款人)',
  `capital_principal` decimal(24,2) DEFAULT '0.00' COMMENT '资方本金',
  `core_price` decimal(24,2) DEFAULT '0.00' COMMENT '核价',
  `rate` decimal(10,8) DEFAULT '0.00000000' COMMENT '利率',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `borrower_end_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '结束日期（借款人）',
  `capital_rate` decimal(10,8) DEFAULT '0.00000000' COMMENT '资方利率',
  `capital_end_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '结束日期（资方）',
  `duration_borrower` int(11) DEFAULT '0' COMMENT '期限（借款人）',
  `duration_capital` int(11) DEFAULT '0' COMMENT '期限（资方）',
  `borrower_accrual` decimal(24,2) DEFAULT '0.00' COMMENT '借款人利息',
  `capital_accrual` decimal(24,2) DEFAULT '0.00' COMMENT '资方利息',
  `net_accrual` decimal(24,2) DEFAULT '0.00' COMMENT '净利息',
  `favorable_amount` decimal(24,2) DEFAULT '0.00' COMMENT '优惠金额',
  `sub_accrual` decimal(24,2) DEFAULT '0.00' COMMENT '利息差',
  `dept_status` int(11) DEFAULT NULL COMMENT '借据状态 0带出账 1 已出账 2预期 3保全中 4结清',
  `repayment_no` varchar(40) DEFAULT NULL COMMENT '还款结算单号',
  `repayment_status` int(11) DEFAULT '0' COMMENT '还款状态 0 待还款 1 已还款',
  `gtm_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gtm_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `memo` varchar(64) DEFAULT NULL COMMENT '备注',
  `repayment_date` datetime DEFAULT NULL COMMENT '还款日期',
  `cal_status` int(11) DEFAULT '0' COMMENT '计算状态 详见CalDebtStatusEnum枚举类的code',
  `today_borrower_accrual` decimal(24,2) DEFAULT '0.00' COMMENT '当天借款人利息',
  `today_capital_accrual` decimal(24,2) DEFAULT '0.00' COMMENT '当天资方利息',
  PRIMARY KEY (`car_debt_flow_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='车辆每日计息';


CREATE TABLE `fp_debt` (
  `debt_id` varchar(20) NOT NULL COMMENT '借据流水号',
  `order_no` varchar(45) NOT NULL COMMENT '订单流水号',
  `contract_no` varchar(45) NOT NULL DEFAULT '' COMMENT '合同流水号',
  `charge_no` varchar(45) NOT NULL DEFAULT '' COMMENT '出账流水号',
  `dealer_no` varchar(45) NOT NULL DEFAULT '' COMMENT '客户编号',
  `dealer_name` varchar(45) NOT NULL DEFAULT '' COMMENT '客户名称',
  `capital_no` varchar(45) NOT NULL DEFAULT '' COMMENT '资方编号',
  `capital_name` varchar(45) NOT NULL DEFAULT '' COMMENT '资方名称',
  `biz_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '金融产品类型',
  `currency` tinyint(4) NOT NULL DEFAULT '1' COMMENT '币种: [1: 人民币, 2: 美元]',
  `loan_amount` decimal(24,2) NOT NULL DEFAULT '0.00' COMMENT '借据金额',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '借据状态: [0: 待放款, 1: 已出帐, 2: 逾期, 3: 保全中, 4: 结清]',
  `expenditure_date` datetime DEFAULT NULL COMMENT '出账日期',
  `due_date` datetime DEFAULT NULL COMMENT '到期日期',
  `real_due_date` datetime DEFAULT NULL COMMENT '实际到期日期',
  `limit_type` tinyint(4) DEFAULT NULL COMMENT '期限类型',
  `limit_count` bigint(20) DEFAULT NULL COMMENT '期限数量',
  `standard_rate` decimal(10,6) DEFAULT NULL COMMENT '基准利率',
  `float_type` varchar(10) DEFAULT '' COMMENT '浮动类型',
  `float_count` decimal(10,6) DEFAULT NULL COMMENT '利率浮动值',
  `reality_rate` decimal(10,6) DEFAULT NULL COMMENT '实际利率',
  `service_tariffing` decimal(10,6) DEFAULT NULL COMMENT '服务费率',
  `service_charge` decimal(24,6) DEFAULT NULL COMMENT '服务费',
  `interest_accrua_type` varchar(20) DEFAULT '' COMMENT '计息方式',
  `interest_period` varchar(20) DEFAULT '' COMMENT '计息周期',
  `repayment_type` varchar(20) DEFAULT '' COMMENT '还款方式',
  `main_guaranty_style` varchar(20) DEFAULT '' COMMENT '主要担保方式',
  `guaranty_style` varchar(45) DEFAULT '' COMMENT '担保方式',
  `assure_amount` decimal(20,6) DEFAULT '0.000000' COMMENT '保证金金额',
  `assure_ratio` decimal(20,6) DEFAULT '0.000000' COMMENT '保证金比例',
  `fair_value` decimal(24,6) DEFAULT '0.000000' COMMENT '抵制物公允价值',
  `risk_exposure_base` decimal(24,6) DEFAULT '0.000000' COMMENT '风险敞口（基础）',
  `risk_exposure_expert` decimal(24,6) DEFAULT '0.000000' COMMENT '风险敞口（高级）',
  `debt_use` varchar(200) DEFAULT NULL COMMENT '借据用途',
  `exhibition_count` tinyint(10) DEFAULT NULL COMMENT '展期次数',
  `exhibition_daytime` bigint(10) DEFAULT NULL COMMENT '展期天数',
  `overdue_principal` decimal(24,6) DEFAULT '0.000000' COMMENT '逾期本金',
  `overdue_interest` decimal(24,6) DEFAULT '0.000000' COMMENT '逾期利息',
  `overdue_principal_and_interest` decimal(24,6) DEFAULT '0.000000' COMMENT '逾期本息和',
  `overdue_time` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '逾期日期',
  `overdue_daytime` bigint(10) DEFAULT NULL COMMENT '逾期天数',
  `add_debt_periods` bigint(10) DEFAULT NULL COMMENT '累计欠款期数',
  `pyatyi_classify_result` varchar(80) DEFAULT NULL COMMENT '五级分类结果',
  `continuous_debt_count` bigint(10) DEFAULT NULL COMMENT '连续欠款期数',
  `final_type` tinyint(4) DEFAULT NULL COMMENT '终结类型',
  `final_date` datetime DEFAULT NULL COMMENT '终结日期',
  `classify_date` datetime DEFAULT NULL COMMENT '分类日期',
  `classify_operator` varchar(45) DEFAULT '' COMMENT '分类操作人',
  `interest_settlement_date` datetime DEFAULT NULL COMMENT '结息日起',
  `interest_settlement_type` varchar(10) DEFAULT '' COMMENT '结息类型',
  `debt_sum_interest` decimal(24,2) DEFAULT '0.00' COMMENT '借据总利息',
  `debt_sum_default_interest` decimal(24,2) DEFAULT '0.00' COMMENT '借据总罚息',
  `debt_sum_compound_interest` decimal(24,2) DEFAULT '0.00' COMMENT '借据总复利',
  `debt_sum_interest_and_principal` decimal(24,2) DEFAULT '0.00' COMMENT '借据总本息和',
  `captical_sum_interest` decimal(24,2) DEFAULT '0.00' COMMENT '资方总贷款利息',
  `captical_sum_interest_and_principal` decimal(24,2) DEFAULT '0.00' COMMENT '资方总贷款本息和',
  `debt_balance_and_principal` decimal(24,2) DEFAULT '0.00' COMMENT '借据余额本金',
  `debt_balance_interest` decimal(24,2) DEFAULT '0.00' COMMENT '借据余额利息',
  `debt_balance_default_interest` decimal(24,2) DEFAULT '0.00' COMMENT '借据余额罚息',
  `debt_balance_interest_and_principal` decimal(24,2) DEFAULT '0.00' COMMENT '借据余额本息和',
  `debt_balance_compound_interest` decimal(24,2) DEFAULT '0.00' COMMENT '借据余额复利',
  `examine_date` datetime DEFAULT NULL COMMENT '检查日期',
  `initial_manager` varchar(20) DEFAULT '' COMMENT '初始管户人',
  `initial_manage_organization` varchar(45) DEFAULT NULL COMMENT '初始管户机构',
  `now_manage_organization` varchar(45) DEFAULT '' COMMENT '目前管户机构',
  `now_manager` varchar(20) DEFAULT '' COMMENT '目前管户人',
  `business_area` varchar(45) DEFAULT '' COMMENT '业务大区',
  `business_business` varchar(20) DEFAULT '' COMMENT '业务经理',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `memo` varchar(128) DEFAULT NULL COMMENT '备注',
  `privilege_price` decimal(24,2) DEFAULT '0.00' COMMENT '优惠金额',
  `has_check_arrvail_time` tinyint(4) DEFAULT '0' COMMENT '是否刷过物流到车日期',
  `arrival_time` bigint(24) DEFAULT NULL,
  `operate_status` tinyint(4) DEFAULT '0' COMMENT '处理状态：0:未处理 1:催收 2:化解 3:保全',
  PRIMARY KEY (`debt_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='资方借据流水表';

CREATE TABLE `fp_statistics` (
  `statistics_id` varchar(20) NOT NULL COMMENT '主键',
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '日期',
  `capital_no` varchar(20) DEFAULT NULL,
  `capital_name` varchar(50) DEFAULT '' COMMENT '资方名称',
  `product_type` tinyint(4) DEFAULT NULL COMMENT '产品类型',
  `current_apply_amount_sum` decimal(24,2) DEFAULT NULL COMMENT '申请金额合计',
  `current_loan_amount_sum` decimal(24,2) DEFAULT NULL COMMENT '贷款存量合计',
  `deposit_amount_sum` decimal(24,2) DEFAULT NULL COMMENT '保证金合计',
  `car_num` int(10) DEFAULT '0' COMMENT '车辆数',
  `car_amount_sum` decimal(24,2) DEFAULT NULL COMMENT '车辆公允价值合计',
  `current_takeout_amount_sum` decimal(24,2) DEFAULT NULL COMMENT '当日出款金额合计',
  `current_return_amount_sum` decimal(24,2) DEFAULT NULL COMMENT '当前回款金额合计',
  `accumulate_loan_amount_sum` decimal(24,2) DEFAULT NULL COMMENT '累计贷款金额合计',
  `accumulate_return_principal_sum` decimal(24,2) DEFAULT NULL COMMENT '累计回收本金合计',
  `accumulate_return_interest_sum` decimal(24,2) DEFAULT NULL COMMENT '累计回收利息合计',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` tinyint(4) DEFAULT '1' COMMENT '-1 删除 1 正常',
  PRIMARY KEY (`statistics_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `fp_overdue_solve` (
  `overdue_solve_id` varchar(31) NOT NULL COMMENT '化解编号',
  `collection_no` varchar(31) DEFAULT NULL COMMENT '催收编号',
  `debt_id` varchar(31) DEFAULT NULL COMMENT '借据id',
  `executor` varchar(31) DEFAULT NULL COMMENT '实施人',
  `execute_id` varchar(31) DEFAULT NULL COMMENT '实施人id',
  `execute_date` timestamp NULL DEFAULT NULL COMMENT '实施日期',
  `car_position` int(11) DEFAULT '0' COMMENT '车辆位置 0未知 1厂家未发车 2物流中 3已入库',
  `debt_principal` decimal(24,2) DEFAULT NULL COMMENT '借据本金',
  `debt_interest` decimal(24,2) DEFAULT NULL COMMENT '借据利息',
  `debt_principal_interest` decimal(24,2) DEFAULT NULL COMMENT '借据本息和',
  `solve_scheme` int(11) DEFAULT '0' COMMENT '解决方案 0未知 1追加保证金 5 暂无',
  `execute_desc` varchar(255) DEFAULT '' COMMENT '实施描述',
  `procedure_position` int(11) DEFAULT '0' COMMENT '手续位置 0未知 1未邮寄 2大区办公室 3杭州公司 4资方 5三方监管',
  `payment_interest` decimal(24,2) DEFAULT NULL COMMENT '还款利息',
  `remark` varchar(255) DEFAULT '' COMMENT '备注',
  `predict_repayment_date` timestamp NULL DEFAULT NULL COMMENT '预计还款时间',
  `car_status` int(11) DEFAULT '0' COMMENT '车辆状态 0未知 1 异常 2 正常',
  `procedure_status` int(11) DEFAULT '0' COMMENT '手续状态 0未知 1 异常 2 正常',
  `car_status_desc` varchar(1024) DEFAULT '' COMMENT '车辆状态描述',
  `procedure_status_desc` varchar(1024) DEFAULT '' COMMENT '手续状态描述',
  `approve_status` int(11) DEFAULT '0' COMMENT '审批状态 0 待审核 1 不通过 2 通过',
  `approve_comment` varchar(255) DEFAULT '' COMMENT '审批意见',
  `status` int(11) DEFAULT NULL,
  `create_source` int(11) DEFAULT '0' COMMENT '创建来源 0 H5 1 后台',
  `gmt_modified` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `gmt_create` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `repayment_promise_letter_list` varchar(1024) DEFAULT NULL COMMENT '还款承诺函 url 和 name 集合',
  `other_file_list` varchar(1024) DEFAULT NULL COMMENT '其他文件 url和name的集合',
  PRIMARY KEY (`overdue_solve_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='化解记录表';

CREATE TABLE `fp_receipt_record` (
  `receipt_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `bank_account` varchar(45) DEFAULT NULL COMMENT '银行账号',
  `bank_open_name` varchar(50) DEFAULT NULL COMMENT '开户行',
  `bank_name` varchar(50) DEFAULT NULL COMMENT '开户名',
  `pay_time` datetime DEFAULT NULL COMMENT '打款时间',
  `pay_times` bigint(5) DEFAULT NULL COMMENT '打款次数',
  `payment_amount` decimal(25,6) DEFAULT '0.000000' COMMENT '还款金额',
  `online_bank` tinyint(4) DEFAULT '0' COMMENT '是否网银',
  `cession_id` varchar(45) DEFAULT NULL COMMENT '项目Id',
  `status` tinyint(4) DEFAULT '0' COMMENT '状态',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `receipt_no` varchar(45) DEFAULT NULL COMMENT '结算单编号',
  `pics` varchar(2048) DEFAULT NULL COMMENT '打款凭证',
  PRIMARY KEY (`receipt_id`)
) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=utf8;